theme: jekyll-theme-minimal
title: Patrick Weidner
logo: 053_Portrait_March2023_RT.jpg
description: Molecular Lifesciences and Bioinformatics at Berlin Institute for Medical Systems Biology
show_downloads: false
