theme: jekyll-theme-minimal
title: Patrick Weidner
logo: Screenshot 2023-04-06 at 11.42.36.png
description: Molecular Lifesciences and Bioinformatics at Berlin Institute for Medical Systems Biology
show_downloads: false
